import type { CategoryCheck } from "./types";

export const categories: CategoryCheck[] = [
	// Code Quality
	{
		id: "typecheck-pass",
		name: "TypeScript typecheck passes",
		domain: "code-quality",
		description: "All workspace typechecks pass",
		weight: 1,
	},
	{
		id: "lint-pass",
		name: "Lint passes without errors",
		domain: "code-quality",
		description: "Biome check exits 0",
		weight: 1,
	},
	{
		id: "no-explicit-any",
		name: "No explicit any",
		domain: "code-quality",
		description: "Avoid `any` types",
		weight: 1,
	},
	{
		id: "no-non-null-assertion",
		name: "No non-null assertions",
		domain: "code-quality",
		description: "Avoid `!` non-null assertions",
		weight: 1,
	},
	{
		id: "no-unused-vars",
		name: "No unused variables",
		domain: "code-quality",
		description: "No unused variables or imports",
		weight: 1,
	},
	{
		id: "no-console-log",
		name: "No leftover console.log",
		domain: "code-quality",
		description: "No debug console.log",
		weight: 1,
	},
	{
		id: "no-duplicate-code",
		name: "No duplicate code blocks",
		domain: "code-quality",
		description: "Avoid duplicate code snippets",
		weight: 1,
	},
	{
		id: "max-file-length",
		name: "File length under threshold",
		domain: "code-quality",
		description: "Source files under 250 lines",
		weight: 1,
	},
	{
		id: "max-function-length",
		name: "Function length under threshold",
		domain: "code-quality",
		description: "Functions under 60 lines",
		weight: 1,
	},
	{
		id: "strict-tsconfig",
		name: "Strict TypeScript config",
		domain: "code-quality",
		description: "tsconfig uses strict",
		weight: 1,
	},
	{
		id: "build-pass",
		name: "Build passes",
		domain: "code-quality",
		description: "Production build succeeds",
		weight: 1,
	},
	{
		id: "test-coverage",
		name: "Tests exist",
		domain: "code-quality",
		description: "At least one test file exists",
		weight: 1,
	},

	// Architecture
	{
		id: "workspace-packages",
		name: "All workspaces have package.json",
		domain: "architecture",
		description: "Every package/app has package.json",
		weight: 1,
	},
	{
		id: "no-circular-deps",
		name: "No circular dependencies",
		domain: "architecture",
		description: "No circular imports within packages",
		weight: 1,
	},
	{
		id: "barrel-exports",
		name: "Barrel exports exist",
		domain: "architecture",
		description: "Packages expose public API via index",
		weight: 1,
	},
	{
		id: "clean-src",
		name: "Clean src/ structure",
		domain: "architecture",
		description: "Source code lives under src/",
		weight: 1,
	},
	{
		id: "no-cross-package-relative",
		name: "No cross-package relative imports",
		domain: "architecture",
		description: "Use workspace packages instead of relative paths",
		weight: 1,
	},
	{
		id: "public-api-docs",
		name: "Public API documented",
		domain: "architecture",
		description: "Exports have TSDoc or README",
		weight: 1,
	},
	{
		id: "consistent-naming",
		name: "Consistent file naming",
		domain: "architecture",
		description: "Files follow kebab-case convention",
		weight: 1,
	},
	{
		id: "root-tsconfig",
		name: "Root tsconfig exists",
		domain: "architecture",
		description: "tsconfig.json or tsconfig.base.json present",
		weight: 1,
	},
	{
		id: "biome-config",
		name: "Biome config present",
		domain: "architecture",
		description: "biome.json or biome.jsonc exists",
		weight: 1,
	},
	{
		id: "no-huge-files",
		name: "No huge files",
		domain: "architecture",
		description: "No source files over 500 lines",
		weight: 1,
	},
	{
		id: "dependency-graph",
		name: "Dependency graph valid",
		domain: "architecture",
		description: "Workspace dependencies reference valid names",
		weight: 1,
	},

	// Dependencies
	{
		id: "lockfile-sync",
		name: "Lockfile in sync",
		domain: "dependencies",
		description: "bun.lock matches package.json",
		weight: 1,
	},
	{
		id: "no-duplicate-deps",
		name: "No duplicate dependencies",
		domain: "dependencies",
		description: "Same dep version across workspaces",
		weight: 1,
	},
	{
		id: "no-missing-peer",
		name: "No missing peer deps",
		domain: "dependencies",
		description: "Peer dependencies declared",
		weight: 1,
	},
	{
		id: "version-present",
		name: "All dependencies have versions",
		domain: "dependencies",
		description: "No versionless dependencies",
		weight: 1,
	},
	{
		id: "no-workspace-star-external",
		name: "No workspace:* in external",
		domain: "dependencies",
		description: "workspace:* only for internal",
		weight: 1,
	},
	{
		id: "no-unused-deps",
		name: "No unused dependencies",
		domain: "dependencies",
		description: "Dependencies referenced in code",
		weight: 1,
	},
	{
		id: "semver-valid",
		name: "Semver versions valid",
		domain: "dependencies",
		description: "Version ranges parseable",
		weight: 1,
	},
	{
		id: "dev-prod-separation",
		name: "Dev/prod separation",
		domain: "dependencies",
		description: "Dev deps not in dependencies",
		weight: 1,
	},
	{
		id: "transitive-size",
		name: "Reasonable dependency size",
		domain: "dependencies",
		description: "No single package over 50MB",
		weight: 1,
	},
	{
		id: "package-manager-field",
		name: "Package manager field",
		domain: "dependencies",
		description: "packageManager defined",
		weight: 1,
	},
	{
		id: "catalog-usage",
		name: "Catalog usage consistent",
		domain: "dependencies",
		description: "catalog: deps resolved",
		weight: 1,
	},

	// Security
	{
		id: "no-env-committed",
		name: "No .env committed",
		domain: "security",
		description: "No .env files in git",
		weight: 1,
	},
	{ id: "no-private-keys", name: "No private keys", domain: "security", description: "No SSH/PEM keys", weight: 1 },
	{
		id: "no-passwords",
		name: "No passwords in code",
		domain: "security",
		description: "No hardcoded passwords",
		weight: 1,
	},
	{ id: "no-tokens", name: "No tokens in code", domain: "security", description: "No API/secret tokens", weight: 1 },
	{ id: "no-eval", name: "No unsafe eval", domain: "security", description: "Avoid eval and new Function", weight: 1 },
	{
		id: "safe-inner-html",
		name: "Safe innerHTML usage",
		domain: "security",
		description: "innerHTML only with trusted content",
		weight: 1,
	},
	{
		id: "no-hardcoded-urls",
		name: "No hardcoded URLs",
		domain: "security",
		description: "Avoid hardcoded URLs in code",
		weight: 1,
	},
	{ id: "no-http", name: "No HTTP URLs", domain: "security", description: "Use HTTPS for external URLs", weight: 1 },
	{
		id: "wrangler-secrets",
		name: "Wrangler secrets not committed",
		domain: "security",
		description: "No wrangler secrets files",
		weight: 1,
	},
	{
		id: "no-secrets-logs",
		name: "No secrets in logs",
		domain: "security",
		description: "No logging of sensitive data",
		weight: 1,
	},
	{
		id: "dependency-vulns",
		name: "No known vulnerable patterns",
		domain: "security",
		description: "Avoid unsafe dependency usage",
		weight: 1,
	},
	{
		id: "csp",
		name: "CSP consideration",
		domain: "security",
		description: "Workers or headers mention CSP",
		weight: 1,
	},

	// Documentation
	{
		id: "root-readme",
		name: "Root README exists",
		domain: "documentation",
		description: "README.md at project root",
		weight: 1,
	},
	{
		id: "agents-md",
		name: "AGENTS.md exists",
		domain: "documentation",
		description: "AGENTS.md or similar guidelines",
		weight: 1,
	},
	{
		id: "package-readmes",
		name: "Package READMEs",
		domain: "documentation",
		description: "Major packages have README",
		weight: 1,
	},
	{
		id: "changelog",
		name: "Changelog exists",
		domain: "documentation",
		description: "CHANGELOG.md or releases",
		weight: 1,
	},
	{
		id: "api-docs",
		name: "API docs",
		domain: "documentation",
		description: "Generated or written API docs",
		weight: 1,
	},
	{
		id: "inline-comments",
		name: "Inline comments",
		domain: "documentation",
		description: "Complex logic has comments",
		weight: 1,
	},
	{
		id: "examples",
		name: "Examples exist",
		domain: "documentation",
		description: "Examples for key features",
		weight: 1,
	},
	{
		id: "website-docs",
		name: "Website docs",
		domain: "documentation",
		description: "Website contains docs",
		weight: 1,
	},
	{
		id: "tsdoc-public",
		name: "TSDoc for public API",
		domain: "documentation",
		description: "Public exports have TSDoc",
		weight: 1,
	},
	{
		id: "contributing",
		name: "Contributing guide",
		domain: "documentation",
		description: "CONTRIBUTING.md or section",
		weight: 1,
	},
	{ id: "license", name: "License", domain: "documentation", description: "LICENSE file present", weight: 1 },
	{
		id: "code-of-conduct",
		name: "Code of conduct",
		domain: "documentation",
		description: "CODE_OF_CONDUCT.md or section",
		weight: 1,
	},

	// Tooling
	{
		id: "no-debugger",
		name: "No debugger statements",
		domain: "code-quality",
		description: "No `debugger;` in code",
		weight: 1,
	},
	{
		id: "gitignore-complete",
		name: "Complete .gitignore",
		domain: "security",
		description: ".gitignore covers dist, node_modules, .env",
		weight: 1,
	},

	// Project config
	{
		id: "ci-cd-pipeline",
		name: "CI/CD pipeline configured",
		domain: "documentation",
		description: ".github/workflows or CI config present",
		weight: 1,
	},
	{
		id: "cloudflare-config",
		name: "Cloudflare config present",
		domain: "documentation",
		description: "wrangler.toml or Cloudflare config exists",
		weight: 1,
	},
	{
		id: "deploy-script",
		name: "Deploy script present",
		domain: "documentation",
		description: "package.json has a deploy script",
		weight: 1,
	},
	{
		id: "package-metadata",
		name: "Package metadata complete",
		domain: "documentation",
		description: "All package.json files have name, version, and description",
		weight: 1,
	},
];

export const domains = ["code-quality", "architecture", "dependencies", "security", "documentation"];
