export interface RegistryItem {
	name: string;
	tag: string;
	description: string;
}
export const registry: RegistryItem[] = [
	{ name: "Accordion", tag: "div", description: "Accordion component" },
	{ name: "Alert", tag: "div", description: "Alert component" },
	{ name: "AspectRatio", tag: "div", description: "AspectRatio component" },
	{ name: "Avatar", tag: "div", description: "Avatar component" },
	{ name: "Badge", tag: "span", description: "Badge component" },
	{ name: "Box", tag: "div", description: "Box component" },
	{ name: "Breadcrumb", tag: "nav", description: "Breadcrumb component" },
	{ name: "Button", tag: "button", description: "Button component" },
	{ name: "Calendar", tag: "div", description: "Calendar component" },
	{ name: "Card", tag: "div", description: "Card component" },
	{ name: "Chart", tag: "div", description: "Chart component" },
	{ name: "Checkbox", tag: "input", description: "Checkbox component" },
	{ name: "Collapsible", tag: "div", description: "Collapsible component" },
	{ name: "Command", tag: "div", description: "Command component" },
	{ name: "CommandPalette", tag: "div", description: "CommandPalette component" },
	{ name: "DataTable", tag: "div", description: "DataTable component" },
	{ name: "DatePicker", tag: "input", description: "DatePicker component" },
	{ name: "Dialog", tag: "div", description: "Dialog component" },
	{ name: "Drawer", tag: "div", description: "Drawer component" },
	{ name: "DropdownMenu", tag: "div", description: "DropdownMenu component" },
	{ name: "FileInput", tag: "input", description: "FileInput component" },
	{ name: "Flex", tag: "div", description: "Flex component" },
	{ name: "Form", tag: "form", description: "Form component" },
	{ name: "FormField", tag: "div", description: "FormField component" },
	{ name: "Grid", tag: "div", description: "Grid component" },
	{ name: "Image", tag: "img", description: "Image component" },
	{ name: "Input", tag: "input", description: "Input component" },
	{ name: "Label", tag: "label", description: "Label component" },
	{ name: "Loading", tag: "div", description: "Loading component" },
	{ name: "Menubar", tag: "div", description: "Menubar component" },
	{ name: "Modal", tag: "div", description: "Modal component" },
	{ name: "Motion", tag: "div", description: "Animation wrapper component" },
	{ name: "NavigationMenu", tag: "nav", description: "NavigationMenu component" },
	{ name: "Notification", tag: "div", description: "Notification component" },
	{ name: "Pagination", tag: "nav", description: "Pagination component" },
	{ name: "Popover", tag: "div", description: "Popover component" },
	{ name: "Progress", tag: "progress", description: "Progress component" },
	{ name: "Radio", tag: "input", description: "Radio component" },
	{ name: "Resizable", tag: "div", description: "Resizable component" },
	{ name: "ScrollArea", tag: "div", description: "ScrollArea component" },
	{ name: "Select", tag: "select", description: "Select component" },
	{ name: "Separator", tag: "hr", description: "Separator component" },
	{ name: "Sheet", tag: "div", description: "Sheet component" },
	{ name: "Skeleton", tag: "div", description: "Skeleton component" },
	{ name: "Slider", tag: "input", description: "Slider component" },
	{ name: "Spinner", tag: "div", description: "Spinner component" },
	{ name: "Stack", tag: "div", description: "Stack component" },
	{ name: "Steps", tag: "div", description: "Steps component" },
	{ name: "Switch", tag: "button", description: "Switch component" },
	{ name: "Table", tag: "table", description: "Table component" },
	{ name: "Tabs", tag: "div", description: "Tabs component" },
	{ name: "Terminal", tag: "div", description: "Terminal component for displaying command output" },
	{ name: "Textarea", tag: "textarea", description: "Textarea component" },
	{ name: "Timeline", tag: "div", description: "Timeline component" },
	{ name: "Toast", tag: "div", description: "Toast component" },
	{ name: "Toaster", tag: "div", description: "Toaster component" },
	{ name: "Toggle", tag: "button", description: "Toggle component" },
	{ name: "ToggleGroup", tag: "div", description: "ToggleGroup component" },
	{ name: "Tooltip", tag: "div", description: "Tooltip component" },
	{ name: "Transition", tag: "div", description: "Transition component" },
	{ name: "TreeView", tag: "ul", description: "TreeView component" },
	{ name: "VirtualList", tag: "div", description: "VirtualList component" },
];
