export interface RegistryItem {
	name: string;
	tag: string;
	description: string;
}
export const registry: RegistryItem[] = [
	{ name: "Accordion", tag: "div", description: "Accordion component" },
	{ name: "Alert", tag: "div", description: "Alert component" },
	{ name: "AspectRatio", tag: "div", description: "Aspect ratio wrapper" },
	{ name: "Avatar", tag: "div", description: "Avatar with image and fallback" },
	{ name: "Badge", tag: "span", description: "Badge component" },
	{ name: "Box", tag: "div", description: "Generic box container" },
	{ name: "Breadcrumb", tag: "nav", description: "Breadcrumb component" },
	{ name: "Button", tag: "button", description: "Button component" },
	{ name: "Calendar", tag: "div", description: "Calendar component" },
	{ name: "Card", tag: "div", description: "Card with header, content, and footer" },
	{ name: "Chart", tag: "div", description: "Chart component" },
	{ name: "Checkbox", tag: "input", description: "Checkbox component" },
	{ name: "Collapsible", tag: "div", description: "Collapsible panel with trigger and content" },
	{ name: "Command", tag: "div", description: "Command component" },
	{ name: "CommandPalette", tag: "div", description: "CommandPalette component" },
	{ name: "DataTable", tag: "div", description: "Data table with sorting and pagination" },
	{ name: "DatePicker", tag: "input", description: "DatePicker component" },
	{ name: "Dialog", tag: "div", description: "Dialog component" },
	{ name: "Drawer", tag: "div", description: "Drawer component" },
	{ name: "DropdownMenu", tag: "div", description: "Dropdown menu" },
	{ name: "FileInput", tag: "input", description: "FileInput component" },
	{ name: "Flex", tag: "div", description: "Flexbox layout container" },
	{ name: "Form", tag: "form", description: "Form component" },
	{ name: "FormField", tag: "div", description: "FormField component" },
	{ name: "Grid", tag: "div", description: "CSS grid layout container" },
	{ name: "Image", tag: "img", description: "Image with fallback" },
	{ name: "Input", tag: "input", description: "Controlled text input" },
	{ name: "Label", tag: "label", description: "Label component" },
	{ name: "Loading", tag: "div", description: "Loading indicator" },
	{ name: "Menubar", tag: "div", description: "Horizontal menu bar" },
	{ name: "Modal", tag: "div", description: "Modal component" },
	{ name: "Motion", tag: "div", description: "Animation wrapper component" },
	{ name: "NavigationMenu", tag: "nav", description: "Navigation menu" },
	{ name: "Notification", tag: "div", description: "Notification component" },
	{ name: "Pagination", tag: "nav", description: "Pagination component" },
	{ name: "Popover", tag: "div", description: "Popover component" },
	{ name: "Progress", tag: "div", description: "Progress bar" },
	{ name: "Radio", tag: "input", description: "Radio component" },
	{ name: "Resizable", tag: "div", description: "Resizable panel with drag handle" },
	{ name: "ScrollArea", tag: "div", description: "Scrollable container" },
	{ name: "Select", tag: "select", description: "Select component" },
	{ name: "Separator", tag: "hr", description: "Horizontal or vertical separator" },
	{ name: "Sheet", tag: "div", description: "Sheet component" },
	{ name: "Skeleton", tag: "div", description: "Loading skeleton placeholder" },
	{ name: "Slider", tag: "input", description: "Slider component" },
	{ name: "Spinner", tag: "div", description: "Loading spinner" },
	{ name: "Stack", tag: "div", description: "Vertical or horizontal stack layout" },
	{ name: "Steps", tag: "div", description: "Steps component" },
	{ name: "Switch", tag: "button", description: "Switch component" },
	{ name: "Table", tag: "table", description: "Semantic table wrapper" },
	{ name: "Tabs", tag: "div", description: "Tabs component" },
	{ name: "Terminal", tag: "div", description: "Terminal component for displaying command output" },
	{ name: "Textarea", tag: "textarea", description: "Textarea component" },
	{ name: "Timeline", tag: "div", description: "Timeline component" },
	{ name: "Toast", tag: "div", description: "Toast component" },
	{ name: "Toaster", tag: "div", description: "Toaster component" },
	{ name: "Toggle", tag: "button", description: "Toggle component" },
	{ name: "ToggleGroup", tag: "div", description: "ToggleGroup component" },
	{ name: "Tooltip", tag: "div", description: "Tooltip component" },
	{ name: "Transition", tag: "div", description: "CSS transition wrapper" },
	{ name: "TreeView", tag: "ul", description: "Tree view with expand/collapse" },
	{ name: "VirtualList", tag: "div", description: "Windowed virtual list" },
];
