export const categories = [
	{
		id: "primitives",
		label: "Primitives",
		items: [
			"Button",
			"Input",
			"Textarea",
			"Select",
			"Checkbox",
			"Radio",
			"Switch",
			"Label",
			"Form",
			"FormField",
			"FileInput",
			"Slider",
			"DatePicker",
			"CheckboxGroup",
			"Combobox",
			"MultiSelect",
			"PinInput",
			"RadioGroup",
			"TagsInput",
		],
	},
	{
		id: "components",
		label: "Components",
		items: [
			"Card",
			"Box",
			"Flex",
			"Grid",
			"Stack",
			"Separator",
			"AspectRatio",
			"Skeleton",
			"Spinner",
			"Loading",
			"Progress",
			"Avatar",
			"Badge",
			"Breadcrumb",
			"Tabs",
			"Pagination",
			"Steps",
			"Timeline",
			"Menubar",
			"NavigationMenu",
			"TreeView",
			"Dialog",
			"Modal",
			"Sheet",
			"Drawer",
			"Tooltip",
			"Popover",
			"Toast",
			"Toaster",
			"Alert",
			"Command",
			"CommandPalette",
			"Notification",
			"Table",
			"DataTable",
			"VirtualList",
			"ScrollArea",
			"Image",
			"Chart",
			"Calendar",
			"Transition",
			"Collapsible",
			"Accordion",
			"DropdownMenu",
			"Toggle",
			"ToggleGroup",
			"Resizable",
			"Terminal",
			"Motion",
			"Kbd",
			"Code",
			"Blockquote",
			"List",
			"ListItem",
			"VisuallyHidden",
			"ProgressCircle",
			"Meter",
			"Stat",
			"SkeletonText",
			"AlertDialog",
			"HoverCard",
			"ContextMenu",
			"SkeletonCircle",
		],
	},
	{
		id: "templates",
		label: "Templates",
		items: ["Form", "Table", "Image", "Transitions"],
	},
];

export const primitiveNames = categories.find((c) => c.id === "primitives")?.items ?? [];
export const componentNames = categories.find((c) => c.id === "components")?.items ?? [];
